---
apiVersion: v1                                                                                                                                                        
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
#  storageClassName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
spec:
  containers:
    - command:
        - sleep
        - "3600d"
      image: alpine:3
      name: alpine-debug
      resources:
        limits:
          cpu: "0.1"
          memory: 500Mi
        requests:
          cpu: "0.05"
          memory: 100Mi
      volumeMounts:
        - mountPath: /data
          name: pvc-test
  volumes:
    - name: pvc-test
      persistentVolumeClaim:
        claimName: pvc-test
